drop table bank_corp purge;

create table bank_corp(
	bank_code  varchar2(20)  constraint bank_corp_bank_code_pk primary key,
	bank_name  varchar2(50)
);

truncate table bank_corp;

select * from bank_corp;

insert into bank_corp values('money', '개인관리');
insert into bank_corp values('fnc001', '한국은행');
insert into bank_corp values('fnc002', '산업은행');
insert into bank_corp values('fnc003', '기업은행');
insert into bank_corp values('fnc004', '국민은행');
insert into bank_corp values('fnc005', 'KEB하나은행');
insert into bank_corp values('fnc006', '수협은행');
insert into bank_corp values('fnc007', '수출입은행');
insert into bank_corp values('fnc008', '농협은행');
insert into bank_corp values('fnc009', '지역농축협');
insert into bank_corp values('fnc010', '우리은행');
insert into bank_corp values('fnc011', '신한은행');
insert into bank_corp values('fnc012', 'SC제일은행');
insert into bank_corp values('fnc013', '한국씨티은행');
insert into bank_corp values('fnc014', '대구은행');
insert into bank_corp values('fnc015', '부산은행');
insert into bank_corp values('fnc016', '광주은행');
insert into bank_corp values('fnc017', '제주은행');
insert into bank_corp values('fnc018', '전북은행');
insert into bank_corp values('fnc019', '경남은행');
insert into bank_corp values('fnc020', '새마을금고');
insert into bank_corp values('fnc021', '신협');
insert into bank_corp values('fnc022', '상호저축은행');
insert into bank_corp values('fnc023', 'D.B.S.');
insert into bank_corp values('fnc024', 'BBVA은행');
insert into bank_corp values('fnc025', '중국농업은행주식유한');
insert into bank_corp values('fnc026', 'B.O.C.');
insert into bank_corp values('fnc027', '스테이트스트리트은행');
insert into bank_corp values('fnc028', 'State Bank');
insert into bank_corp values('fnc029', '중국광대은행');
insert into bank_corp values('fnc030', 'Yamaguchi');
insert into bank_corp values('fnc031', '바덴뷔르템베르크은행');
insert into bank_corp values('fnc032', 'BNPParibas');
insert into bank_corp values('fnc033', 'AMEX');
insert into bank_corp values('fnc034', 'ING Bank');
insert into bank_corp values('fnc035', 'I.O.B.');
insert into bank_corp values('fnc036', 'U.O.B');
insert into bank_corp values('fnc037', 'SEPAC');
insert into bank_corp values('fnc038', 'N.B.C.');
insert into bank_corp values('fnc039', 'Barclays');
insert into bank_corp values('fnc040', 'I.B.S.');
insert into bank_corp values('fnc041', 'NovaScotia');
insert into bank_corp values('fnc042', '골드만삭스인터내셔널');
insert into bank_corp values('fnc043', '크레디아그리콜뱅크');
insert into bank_corp values('fnc044', 'B.T.C.');
insert into bank_corp values('fnc045', 'MitsuiSumi');
insert into bank_corp values('fnc046', 'R.B.C.');
insert into bank_corp values('fnc047', 'UBS');
insert into bank_corp values('fnc048', 'B.O.M.');
insert into bank_corp values('fnc049', 'U.B.A.F.');
insert into bank_corp values('fnc050', 'MELLAT');
insert into bank_corp values('fnc051', 'TOKAI');
insert into bank_corp values('fnc052', 'S.G.B.');
insert into bank_corp values('fnc053', 'WESTPAC');
insert into bank_corp values('fnc054', 'F.N.B.B.');
insert into bank_corp values('fnc055', 'N.B.P.');
insert into bank_corp values('fnc056', 'A.B.L.');
insert into bank_corp values('fnc057', 'ASAHI');
insert into bank_corp values('fnc058', 'MITSUBISHI');
insert into bank_corp values('fnc059', '메릴린치인터내셔널');
insert into bank_corp values('fnc060', '맥쿼리은행');
insert into bank_corp values('fnc061', 'B.O.H.');
insert into bank_corp values('fnc062', 'OCBC Bank');
insert into bank_corp values('fnc063', 'FICAL');
insert into bank_corp values('fnc064', '리먼브러더스');
insert into bank_corp values('fnc065', 'A.N.Z.');
insert into bank_corp values('fnc066', 'BNY MELLON');
insert into bank_corp values('fnc067', 'N.W.B');
insert into bank_corp values('fnc068', 'DAIWA');
insert into bank_corp values('fnc069', 'L.T.C.B.');
insert into bank_corp values('fnc070', 'METROBANK');
insert into bank_corp values('fnc071', '메트로은행');
insert into bank_corp values('fnc072', 'CreditSuis');
insert into bank_corp values('fnc073', 'Wachovia');
insert into bank_corp values('fnc074', '중국건설은행');
insert into bank_corp values('fnc075', '중국교통은행');
insert into bank_corp values('fnc076', '모간스탠리');
insert into bank_corp values('fnc077', 'HSBC');
insert into bank_corp values('fnc078', '도이치은행');
insert into bank_corp values('fnc079', '알비에스피엘씨');
insert into bank_corp values('fnc080', 'JP모간체이스');
insert into bank_corp values('fnc081', '미즈호은행');
insert into bank_corp values('fnc082', '미쓰비시도쿄UFJ은');
insert into bank_corp values('fnc083', 'B.O.A');
insert into bank_corp values('fnc084', '비엔피파리바');
insert into bank_corp values('fnc085', '중국공상은행');
insert into bank_corp values('fnc086', '중국은행');
insert into bank_corp values('fnc087', '산림조합');
insert into bank_corp values('fnc088', '대화은행');
insert into bank_corp values('fnc089', '우체국');
insert into bank_corp values('fnc090', '신용보증기금');
insert into bank_corp values('fnc091', '기술보증기금');
insert into bank_corp values('fnc092', '케이뱅크');
insert into bank_corp values('fnc093', '카카오뱅크');
insert into bank_corp values('fnc094', '서울보증보험');
insert into bank_corp values('fnc095', '금융결제원');
insert into bank_corp values('fnc096', '유안타증권');
insert into bank_corp values('fnc097', 'KB증권');
insert into bank_corp values('fnc098', 'KTB투자증권');
insert into bank_corp values('fnc099', '미래에셋대우');
insert into bank_corp values('fnc100', '삼성증권');
insert into bank_corp values('fnc101', '한국투자증권');
insert into bank_corp values('fnc102', 'NH투자증권');
insert into bank_corp values('fnc103', '교보증권');
insert into bank_corp values('fnc104', '하이투자증권');
insert into bank_corp values('fnc105', '현대차투자증권');
insert into bank_corp values('fnc106', '키움증권');
insert into bank_corp values('fnc107', '이베스트투자증권');
insert into bank_corp values('fnc108', '에스케이증권');
insert into bank_corp values('fnc109', '대신증권');
insert into bank_corp values('fnc110', '메리츠종합금융증권');
insert into bank_corp values('fnc111', '한화투자증권');
insert into bank_corp values('fnc112', '하나금융투자');
insert into bank_corp values('fnc113', '신한금융투자');
insert into bank_corp values('fnc114', 'DB금융투자');
insert into bank_corp values('fnc115', '유진투자증권');
insert into bank_corp values('fnc116', '부국증권');
insert into bank_corp values('fnc117', '신영증권');
insert into bank_corp values('fnc118', '케이프투자증권');
insert into bank_corp values('fnc119', '펀드온라인코리아');
insert into bank_corp values('fnc120', '미래에셋생명');
insert into bank_corp values('fnc121', '메리츠화재');
insert into bank_corp values('fnc122', '삼성생명');
